if: type != push OR branch = master

services:
  - docker

language: bash

script:
  - docker build -t $IMAGE_NAME .
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
