dist: trusty
sudo: required
language: bash

stages:
  - name: verify
  - name: build
    if: branch = master

jobs:
  include:
    - stage: verify
      script:
      - docker build -t angular-spring-heroes .
      - docker images
    - stage: build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_ORG/angular-spring-heroes .
      - docker images
      - docker push $DOCKER_ORG/angular-spring-heroes
